---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      network:
        - ["private_network", {ip: "192.168.38.34"}]
      customize:
        memory: 1536
        natdnshostresolver1: "on"

suites:
  - name: server
    run_list:
      - recipe[chef_server::server]
    attributes:
